name: "Build"
on:
  push:
    branches:
      - "stable"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  pull_request_review:
    types:
      - submitted
jobs:
  Build-Server-Jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '8'
      - name: Run Gradle
        run: ./gradlew && ./gradlew jar
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: Grasscutter
          path: grasscutter.jar
      
